# Generated by Django 3.1.3 on 2020-12-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
